// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DeleteSightingReducer from "../delete_sighting_reducer";
import RegisterUserReducer from "../register_user_reducer";
import ReportSightingReducer from "../report_sighting_reducer";
import UpdateSightingReducer from "../update_sighting_reducer";

export type DeleteSightingParams = __Infer<typeof DeleteSightingReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type ReportSightingParams = __Infer<typeof ReportSightingReducer>;
export type UpdateSightingParams = __Infer<typeof UpdateSightingReducer>;

