// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Sighting = __t.object("Sighting", {
  id: __t.u64(),
  userIdentity: __t.identity(),
  speciesId: __t.u32(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  timestamp: __t.u64(),
  description: __t.string(),
  podSize: __t.u32(),
});
export type Sighting = __Infer<typeof Sighting>;

export const Species = __t.object("Species", {
  id: __t.u32(),
  name: __t.string(),
  scientificName: __t.string(),
  category: __t.string(),
});
export type Species = __Infer<typeof Species>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
});
export type User = __Infer<typeof User>;

